# Services:
# -Alex: the provided bin packing algorithm. Puts items in the first bin with sufficient space
# -Carla: a modified version of Alex which places items in the most full bin wit sufficient space
# -storage: creates and stores test data cases so to allow comparing Alex and Carla on the same data
# -web: contains the code for running tests on Alex and Carla and comparing their results

# Only web is exposed to the outside with port 7555 mapping to internal port 5000. Port 5000 is used internally for all services.
# Pages can access each other at http://<service_name>:5000/<url>


services:
    web:
        build: ./eval
        ports:
          - "7555:5000"
    alex:
        build: ./alex
        expose:
          - "5000"

    carla:
        build: ./carla
        expose:
          - "5000"

    storage:
        build: ./storage
        expose:
          - "5000"
    
